def generate_profile(age: int):
    """Generates age profile based on the provided age.

    Function categorizes age into standard groups:
    - Children (0-12 years)
    - Teenagers (13-19 years)
    - Adult (20+ years)

    Keyword arguments:
        age (int): Person's age. Should be an integer.

    Returns:
        str: String with age category name:
            - "Child" for ages 0-12
            - "Teenager" for ages 13-19
            - "Adult" for ages 20+
            - "-" for negative ages (invalid input)
    """
    if age < 0: return "-"
    if age <= 12: return "Child"
    if age <= 19: return "Teenager" 
    return "Adult"
         
def profile_summary(dictionary: dict):
    """Prints a formated summary of a user profile.

    The function processes the profile dictionary with the following features:
    - Formats and prints all key-value pairs from the profile dictionary generated by main()
    - Handles the 'Hobbies' key specially by:
        * Displaying each hobby as a bullet point 
        * Showing the count of hobbies 
        * Displaying a default message if hobbies list is empty

    Keyword arguments:
        dictinary (dict): Profile data generated by main() function with keys:
            - 'Name' (str): User's full name
            - 'Age' (int): Calculated current age
            - 'Life Stage' (str): Age category from generate_profile()
            - 'Hobbies' (list): List of hobby strings entered by user

    Returns:
         None: This function only prints output to console and does not return any value.          
    """
    print("-"*3)
    print("Profile Summary:")
    # Process each key-value pair in the profile dictionary
    for key,value in dictionary.items():
        if key == "Hobbies":
            # Check if hobbies list is not empty
            if value:
                # Display hobbies count and list them with bullet points
                print(f"Favorite Hobbies({len(value)}):")
                for i in value:
                    print(f"- {i}")  
            else:
                # Show message when no hobbies provided
                print("You didn't mention any hobbies")
        else:   
            # Display regular key-value pairs in standard format 
            print(f"{key}: {value}")
    print("-"*3)        

def main():
    """
    Main function that collects user profile data and displays a summary
    
    The function performs the following steps:
    - Collects user's full name via input
    - Collects and processes birth year to calculate current age
    - Collects multiple hobbies until user types 'stop'
    - Determines life stage using generate_profile() function
    - Creates a comprehensive user profile dictionary
    - Displays formatted summary using profile_summary() function

    Key features:
    - Reads multiple inputs from the user
    - Prints output through profile_summary() function
    - Uses current year 2025 for age calculation

    Returns:
    None: This function orchestrates the profile creation process but does not return any value.
    """
    user_name = input("Enter your full name: ")  
    birth_year_str = input("Enter your birth year: ")
    birth_year = int(birth_year_str)
    current_age = 2025 - birth_year
    hobbies = []
    # Collect hobbies until user enters 'stop'
    while (hobby := input("Enter a favorite hobby or type 'stop' to finish: ")).lower() != "stop":
        hobbies.append(hobby)
    life_stage = generate_profile(current_age) 
    user_profile={"Name": user_name, 
                  "Age": current_age,
                  "Life Stage": life_stage,
                  "Hobbies": hobbies }
    profile_summary(user_profile)
# Program entry point - starts the user profile creation process
main()